mineral_catalog_project/config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('mineral_catalog.minerals.urls', namespace='minerals')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

mineral_catalog_project/mineral_catalog/minerals/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'detail/(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'random', views.random_mineral, name='random_mineral'),
    url(r'search/color/user',
        views.search_color_user, name='search_color_user'),
    url(r'search/color/(?P<pk>[\w\-]+)/$',
        views.search_color_selected, name='search_color_selected'),
    url(r'search/color', views.search_color, name='search_color'),
    url(r'search/crystalsystem/(?P<pk>[\w\-]+)/$',
        views.search_crystal_system_selected,
        name='search_crystal_system_selected'),
    url(r'search/crystalsystem',
        views.search_crystal_system, name='search_crystal_system'),
    url(r'search/letter/(?P<pk>[\w\-]+)/$',
        views.search_letter_selected, name='search_letter_selected'),
    url(r'search/letter', views.search_letter, name='search_letter'),
    url(r'search/group/(?P<pk>[\w\-]+)/$',
        views.search_group_selected, name='search_group_selected'),
    url(r'search/group', views.search_group, name='search_group'),
    url(r'search/term/',
        views.search_term_selected, name='search_term_selected'),
    url(r'search/help/', views.search_help, name='search_help'),
    url(r'search', views.search, name='search'),
]

mineral_catalog_project/mineral_catalog/minerals/models.py
from django.db import models


class Mineral(models.Model):
    '''This is the model for a mineral.'''
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255, blank=True)
    image_caption = models.CharField(max_length=255, blank=True)
    category = models.CharField(max_length=255, blank=True)
    formula = models.CharField(max_length=255, blank=True)
    strunz_classification = models.CharField(max_length=255, blank=True)
    color = models.CharField(max_length=255, blank=True)
    crystal_system = models.CharField(max_length=255, blank=True)
    unit_cell = models.CharField(max_length=255, blank=True)
    crystal_symmetry = models.CharField(max_length=255, blank=True)
    cleavage = models.CharField(max_length=255, blank=True)
    mohs_scale_hardness = models.CharField(max_length=255, blank=True)
    luster = models.CharField(max_length=255, blank=True)
    streak = models.CharField(max_length=255, blank=True)
    diaphaneity = models.CharField(max_length=255, blank=True)
    optical_properties = models.CharField(max_length=255, blank=True)
    refractive_index = models.CharField(max_length=255, blank=True)
    crystal_habit = models.CharField(max_length=255, blank=True)
    specific_gravity = models.CharField(max_length=255, blank=True)
    group = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return self.name

mineral_catalog_project/mineral_catalog/minerals/views.py
import collections
import string
import random

from django.db.models import Q
from django.shortcuts import get_object_or_404, render

from .models import Mineral


def home(request):
    '''This is the homepage for the minerals app.'''
    mineral = Mineral.objects.all()
    content_title = ("Here are all " + str(len(mineral)) +
                     " minerals in the database")
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': mineral, 'content_title': content_title})


def detail(request, pk):
    '''This is the detail page for the minerals app.'''
    mineral = get_object_or_404(Mineral, pk=pk)
    return render(request, 'minerals/mineral_detail.html', {'mineral':
                                                            mineral})


def random_mineral(request):
    '''This returns a random detail page for a mineral in the database.'''
    all_minerals = Mineral.objects.all()
    mineral = random.choice(all_minerals)
    return render(request, 'minerals/mineral_detail.html', {'mineral':
                                                            mineral})


def search(request):
    '''This takes the user to the advanced search page.'''
    return render(request, 'minerals/search.html')


def search_help(request):
    '''This takes the user to the search help page.'''
    return render(request, 'minerals/help.html')


def search_color(request):
    '''This takes the user to the search by color page.'''
    # This is a list of collors guarenteed to get results.
    colors = ['amber', 'amethyst', 'apple', 'azure', 'black', 'blue', 'blood',
              'bluish', 'brass', 'bronze', 'brown', 'colorless', 'copper',
              'cream', 'crimson', 'cyan', 'dark', 'dark', 'dull', 'dull',
              'emerald', 'gold', 'gray', 'green', 'greenish', 'grey', 'indigo',
              'iridescent', 'lavender', 'lead', 'metallic', 'olive', 'orange',
              'peach', 'pale', 'pink', 'pistachio', 'purple', 'purplish',
              'red', 'rose', 'rosy', 'rosy', 'ruby', 'silver', 'steel',
              'steel', 'transparent', 'turquoise', 'violet', 'white', 'yellow']

    colors = collections.OrderedDict.fromkeys(colors)
    return render(request, 'minerals/search_color.html',
                  {'colors': colors})


def search_color_selected(request, pk=None):
    '''This takes the user to crystal system search page.'''
    minerals = Mineral.objects.all().filter(color__icontains=pk)
    content_title = (
        (str(len(minerals)) + " results for the color  "))
    content_end = pk
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'content_title': content_title,
                   'content_end': content_end})


def search_color_user(request):
    '''This returns the search results for a color the user entered.'''
    search = request.GET.get('search')
    # This searches for the user's color.
    minerals = Mineral.objects.all().filter(color__icontains=search)

    content_title = (
        (str(len(minerals)) + " results for the color "))
    content_end = search

    return render(
        request, 'minerals/mineral_list.html',
        {'minerals': minerals, 'content_title': content_title,
         'content_end': content_end})


def search_crystal_system(request):
    '''This takes the user to crystal system search page.'''
    content_title = 'Please select the crystal system you want'
    return render(request, 'minerals/search_crystal_system.html',
                  {'content_title': content_title})


def search_crystal_system_selected(request, pk):
    '''This takes the user to crystal system search page.'''
    minerals = Mineral.objects.all().filter(crystal_system__icontains=pk)
    content_title = (
        (str(len(minerals)) + " results for the crystal system  "))
    content_end = (pk.title())
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals, 'content_title': content_title,
                   'content_end': content_end})


def search_letter(request):
    '''This takes the user to the search letter page.'''
    # This creates an OrderedDict for each of the uppercase letters.
    letters = string.ascii_uppercase
    letters = collections.OrderedDict.fromkeys(letters)

    content_title = "Please select the first letter for the mineral you want."
    return render(request, 'minerals/search_letter.html',
                  {'letters': letters, 'content_title': content_title})


def search_letter_selected(request, pk):
    '''This returns the search results for a letter the user has chosen.'''
    mineral_list = Mineral.objects.all()
    minerals = []

    # This gets every mineral that matches the pk.
    for item in mineral_list:
        if item.name[0].upper() == pk.upper():
            minerals.append(item)

    content_title = (
        (str(len(minerals)) + " results for the letter  "))
    content_end = (pk.title())

    # This is to allow the user to see which group is selected in the
    # group navagation bar.
    letter = {}
    letter['{}'.format(pk.lower())] = 'True'

    return render(
        request, 'minerals/mineral_list.html',
        {'minerals': minerals, 'content_title': content_title,
         'content_end': content_end, 'letter': letter})


def search_group(request):
    '''This takes the user to the search group page.'''
    return render(request,
                  'minerals/search_group.html')


def search_group_selected(request, pk):
    '''This returns the search results for a group the user searched.'''
    minerals = Mineral.objects.all().filter(group__icontains=pk)

    # This is to allow the user to see which group is selected in the
    # group navagation bar.
    group = {}
    group['{}'.format(pk.lower())] = 'True'

    # This checks to see if the user is searching by Native Elements or
    # Organic Minerals and changes the pk name if so.
    if pk.lower() == 'organic':
        pk = 'Organic Minerals'
    elif pk.lower() == 'native':
        pk = 'Native Elements'

    content_title = (
        (str(len(minerals)) + " results for the group "))
    content_end = (pk.title())

    return render(
        request, 'minerals/mineral_list.html',
        {'minerals': minerals, 'content_title': content_title,
         'content_end': content_end, 'group': group})


def search_term_selected(request):
    '''This returns the search results for a term the user searched.'''
    search = request.GET.get('search')
    # This searches every characteristic a mineral can have.
    minerals = Mineral.objects.all().filter(
        Q(name__icontains=search) | Q(image_caption__icontains=search) |
        Q(category__icontains=search) | Q(formula__icontains=search) |
        Q(strunz_classification__icontains=search) |
        Q(color__icontains=search) | Q(crystal_system__icontains=search) |
        Q(cleavage__icontains=search) |
        Q(mohs_scale_hardness__icontains=search) |
        Q(luster__icontains=search) | Q(streak__icontains=search) |
        Q(diaphaneity__icontains=search) |
        Q(optical_properties__icontains=search) |
        Q(refractive_index__icontains=search) |
        Q(crystal_habit__icontains=search) |
        Q(specific_gravity__icontains=search) | Q(group__icontains=search))

    content_title = (
        (str(len(minerals)) + " results for the search term "))
    content_end = search

    return render(
        request, 'minerals/mineral_list.html',
        {'minerals': minerals, 'content_title': content_title,
         'content_end': content_end})

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/help.html
{% extends "layout.html" %}


{% block content_title %}
  <p class="search__header">This page is for help on how to search the Mineral Catalog.</p>
{% endblock %}

{% block content %}
  <p class="help__paragraph">To search the Mineral Catalog for any data that a mineral may contain
     (Search all data by Term) please use the box under the main Mineral Catalog
      logo. Just type in your query in one word and press enter.
  </p>
  <p class="help__paragraph"> The Search Alphabetically option allows you to choose the first starting letter for
    the minerals you want to search for.
  </p>
  <p class="help__paragraph"> The Search by Color option allows you to choose or
    search for a color of choice. If searching only use one word.
  </p>
  <p class="help__paragraph"> Search by Crystal System lets you search
    the Mineral Catalog via the seven kinds of Crystal Systems.
  </p>
  <p class="help__paragraph"> Seaching by Group allows you to choose a Group you want to filter the
    Mineral Catalog by.
  </p>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/mineral_detail.html
{% extends "layout.html" %}
{% load static from staticfiles %}

{% block div %}<div class="bounds bounds--small">{% endblock %}

{% block content %}
</div>
<div class="grid-100 mineral__container">
<h1 class="mineral__name"><a href="{% url 'minerals:detail' pk=mineral.pk %}">{{ mineral|title }}</a></h1>
<div class="mineral__image-bg">
  {% with '/minerals/images/'|add:mineral.name|add:'.jpg' as mineral_image %}
  <img class="mineral__image" src= {% static mineral_image %}>
  <p class="mineral__caption">{{ mineral.image_caption}}</p>
  {% endwith %}
</div>
<div class="mineral__table-container">
  <table class="mineral__table">
    {% if mineral.color %}
    <tr>
      <td class="mineral__category">Color</td>
      <td>{{ mineral.color}}</td>
    </tr>
    {% endif %}
    {% if mineral.formula %}
    <tr>
      <td class="mineral__category">Formula</td>
      <td>{{ mineral.formula|safe}}</td>
    </tr>
    {% endif %}
    {% if mineral.category %}
    <tr>
      <td class="mineral__category">Category</td>
      <td>{{ mineral.category}}</td>
    </tr>
    {% endif %}
    {% if mineral.cleavage %}
    <tr>
      <td class="mineral__category">Cleavage</td>
      <td>{{ mineral.cleavage}}</td>
    </tr>
    {% endif %}
    {% if mineral.crystal_habit %}
    <tr>
      <td class="mineral__category">Crystal Habit</td>
      <td>{{ mineral.crystal_habit}}</td>
    </tr>
    {% endif %}
    {% if mineral.crystal_symmetry %}
    <tr>
      <td class="mineral__category">Crystal Symmetry</td>
      <td>{{ mineral.crystal_symmetry}}</td>
    </tr>
    {% endif %}
    {% if mineral.crystal_system %}
    <tr>
      <td class="mineral__category">Crystal System</td>
      <td>{{ mineral.crystal_system}}</td>
    </tr>
    {% endif %}
    {% if mineral.diaphaneity %}
    <tr>
      <td class="mineral__category">Diaphaneity</td>
      <td>{{ mineral.diaphaneity}}</td>
    </tr>
    {% endif %}
    {% if mineral.group %}
    <tr>
      <td class="mineral__category">Group</td>
      <td>{{ mineral.group}}</td>
    </tr>
    {% endif %}
    {% if mineral.luster %}
    <tr>
      <td class="mineral__category">Luster</td>
      <td>{{ mineral.luster}}</td>
    </tr>
    {% endif %}
    {% if mineral.mohs_scale_hardness %}
    <tr>
      <td class="mineral__category">Mohs Scale Hardness</td>
      <td>{{ mineral.mohs_scale_hardness}}</td>
    </tr>
    {% endif %}
    {% if mineral.optical_properties %}
    <tr>
      <td class="mineral__category">Optical Properties</td>
      <td>{{ mineral.optical_properties}}</td>
    </tr>
    {% endif %}
    {% if mineral.refractive_index %}
    <tr>
      <td class="mineral__category">Refractive Index</td>
      <td>{{ mineral.refractive_index}}</td>
    </tr>
    {% endif %}
    {% if mineral.specific_gravity %}
    <tr>
      <td class="mineral__category">Specific Gravity</td>
      <td>{{ mineral.specific_gravity}}</td>
    </tr>
    {% endif %}
    {% if mineral.streak %}
    <tr>
      <td class="mineral__category">Streak</td>
      <td>{{ mineral.streak}}</td>
    </tr>
    {% endif %}
    {% if mineral.strunz_classification %}
    <tr>
      <td class="mineral__category">Strunz Classification</td>
      <td>{{ mineral.strunz_classification}}</td>
    </tr>
    {% endif %}
    {% if mineral.unit_cell %}
    <tr>
      <td class="mineral__category">Unit Cell</td>
      <td>{{ mineral.unit_cell}}</td>
    </tr>
    {% endif %}
  </table>
</div>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/mineral_list.html
{% extends "layout.html" %}

{% block content_title %}
  <p class="search__header">{{ content_title }}<b>{{ content_end }}</b></p>
{% endblock %}

{% block content %}
<ul class="minerals__container">

  {% for mineral in minerals %}
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:detail' pk=mineral.pk %}">{{mineral.name}}</a>
  </li>
  {% endfor %}

</ul>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/search.html
{% extends "layout.html" %}


{% block content_title %}
  <p class="search__header">Welcome to the search page! Please select a search option below.</p>
{% endblock %}

{% block content %}
<ul class="minerals__container">
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_letter' %}">Search Alphabetically</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_color' %}">Search by Color</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system' %}">Search by Crystal System</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group' %}">Search by Group</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_help' %}">Search all data by Term</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_help' %}">Searching help</a>
  </li>
</ul>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/search_color.html
{% extends "layout.html" %}

{% block content_title %}
  <p class="search__header">{{ content_title }}</p>

  <form action="{% url 'minerals:search_color_user' %}" method="GET">
  <p class="logo__text text-centered">
    <input class="large__search__box" placeholder="Search colors here or use results bellow" name="search">
  </p>
  </form>
{% endblock content_title %}

{% block content %}
<ul class="minerals__container">
  {% for color in colors %}
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_color_selected' pk=color %}">{{color}}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/search_crystal_system.html
{% extends "layout.html" %}

{% block content_title %}
  <p class="search__header">{{ content_title }}</p>
{% endblock %}

{% block content %}
<ul class="minerals__container">
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="cubic" %}">Cubic</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="hexagonal" %}">Hexagonal</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="monoclinic" %}">Monoclinic</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="triclinic" %}">Triclinic</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="tetragonal" %}">Tetragonal</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="trigonal" %}">Trigonal</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_crystal_system_selected' pk="orthorhombic" %}">Orthorhombic</a>
  </li>

</ul>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/search_group.html
{% extends "layout.html" %}

{% block content_title %}
  <p class="search__header">Please select the group you want to see below.</p>
{% endblock %}

{% block content %}
<ul class="minerals__container">
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Arsenates" %}">Arsenates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Borates" %}">Borates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Carbonates" %}">Carbonates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Halides" %}">Halides</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Native" %}">Native Elements</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Organic" %}">Organic Minerals</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="oxides" %}">Oxides</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Silicates" %}">Silicates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Sulfates" %}">Sulfates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Sulfides" %}">Sulfides</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Sulfosalts" %}">Sulfosalts</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Phosphates" %}">Phosphates</a>
  </li>
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_group_selected' pk="Other" %}">Other</a>
  </li>
</ul>
{% endblock %}

mineral_catalog_project/mineral_catalog/minerals/templates/minerals/search_letter.html
{% extends "layout.html" %}

{% block content_title %}
  <p class="search__header">{{ content_title }}</p>
{% endblock %}

{% block content %}
<ul class="minerals__container">
  {% for letter in letters %}
  <li class="minerals__item">
    <a class="minerals__anchor" href="{% url 'minerals:search_letter_selected' pk=letter %}">{{letter}}</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}